# Generated by Django 4.1 on 2022-08-06 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reference", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referencerequest",
            name="requester",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="referencerequest",
            name="requester_company",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="user.company"),
        ),
    ]
