name: ci
on:
  push:
    branches:
      - main
jobs:
  run-test-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - run: touch user/.env
      - run : echo CI_TEST_PASS=${{ secrets.CI_TEST_PASS }} >> user/.env
      - run: pip install -r requirements.txt
      - run: pytest
